%% Flugdynamik Airbus A300
% Zustandsraum Laengsbewegung
load("Brockhaus2011/Airbus A300\A3_LB_Zustandsraum.mat","ZR");

% Anstellwinkelschwingung (eta -> alpha)
AWS = -ss(ZR.A(1:2,1:2), ...
         ZR.B(1:2,2), ...
         ZR.C(2,1:2), ...
         ZR.D(2,2), ...
         "StateName", ZR.StateName(1:2), ...
         "InputName", ZR.InputName(2), ...
         "OutputName",ZR.OutputName(2) ...
);

% Phugoidschwingung (f -> V)
Phugoid = ss(ZR.A(3:4,3:4), ...
             ZR.B(3:4,1), ...
             ZR.C(3,3:4), ...
             ZR.D(3,1), ...
             "StateName", ZR.StateName(3:4), ...
             "InputName", ZR.InputName(1), ...
             "OutputName",ZR.OutputName(3) ...
);

